const Addresses = [
  {
    id: 1,
    name: "חנה",
    lastname: "סיגאוי",
    phone: "0548333375",
    city: "תל אביב יפו",
    neighborhood: "הצפון הישן",
    street: "סירקין",
    homenumber: "13",
    adresscomments: "מול קיוסק ציונה",
    additionalneeds: "שמיכות",
    isproblematic: true,
    howmanypeople: "2",
    kosher: true,
    parve: false,
    vegan: false,
    sugerfree: true,
    lactosefree: false,
    glutenfree: false,
    peanutfree: false,
    nutsfree: true,
    comments: "",
    priority: "1",
  },
  {
    id: 2,
    name: "חדוה",
    lastname: "אסולין",
    phone: "0542243775",
    city: "תל אביב יפו",
    neighborhood: "נווה שאנן",
    street: "לוינסקי",
    homenumber: "4",
    adresscomments: "",
    additionalneeds: "",
    isproblematic: false,
    howmanypeople: "2",
    kosher: false,
    parve: false,
    vegan: true,
    sugerfree: false,
    lactosefree: false,
    glutenfree: true,
    peanutfree: false,
    nutsfree: true,
    comments: "",
    priority: "1",
  },
  {
    id: 3,
    name: "אנה",
    lastname: "כהן",
    phone: "0549543979",
    city: "חיפה",
    neighborhood: "נווה שאנן",
    street: "חניתה",
    homenumber: "27",
    adresscomments: "",
    additionalneeds: "",
    isproblematic: false,
    howmanypeople: "2",
    kosher: false,
    parve: false,
    vegan: false,
    sugerfree: true,
    lactosefree: true,
    glutenfree: false,
    peanutfree: false,
    nutsfree: false,
    comments: "",
    priority: "2",
  },
  {
    id: 4,
    name: "גידי",
    lastname: "אברהמוב",
    phone: "0503443775",
    city: "חיפה",
    neighborhood: "בת גלים",
    street: "לוץ שרל",
    homenumber: "3",
    adresscomments: "",
    additionalneeds: "",
    isproblematic: false,
    howmanypeople: false,
    kosher: false,
    parve: false,
    vegan: false,
    sugerfree: false,
    lactosefree: false,
    glutenfree: false,
    peanutfree: false,
    nutsfree: false,
    comments: "",
    priority: "2",
  },
  {
    id: 5,
    name: "הודיה",
    lastname: "",
    phone: "0540543005",
    city: "כפר סבא",
    neighborhood: "אליעזר",
    street: "טשרנחובסקי",
    homenumber: "24",
    adresscomments: "",
    additionalneeds: "",
    isproblematic: false,
    howmanypeople: "3",
    kosher: false,
    parve: false,
    vegan: true,
    sugerfree: false,
    lactosefree: false,
    glutenfree: false,
    peanutfree: false,
    nutsfree: false,
    comments: "משפחה של 3 אנשים הבנות אוהבות עוגיות שוקולד",
    priority: "1",
  },
  {
    id: 6,
    firstname: "אדווה",
    lastname: "כוהן",
    phone: "0528543115",
    city: "תל אביב יפו",
    neighborhood: "נווה שאנן",
    street: "הרכבת",
    homenumber: "4",
    adresscomments: "",
    additionalneeds: "",
    isproblematic: false,
    howmanypeople: "2",
    kosher: false,
    parve: false,
    vegan: true,
    sugerfree: false,
    lactosefree: false,
    glutenfree: true,
    peanutfree: false,
    nutsfree: true,
    comments: "",
    priority: "1",
  },

  {
    id: 7,
    firstname: "אברהם",
    lastname: "",
    phone: "0528443115",
    city: "תל אביב יפו",
    neighborhood: "פלורנטין",
    street: "הרצל",
    homenumber: "4",
    adresscomments: "",
    additionalneeds: "",
    isproblematic: false,
    howmanypeople: "2",
    kosher: false,
    parve: false,
    vegan: true,
    sugerfree: false,
    lactosefree: false,
    glutenfree: true,
    peanutfree: false,
    nutsfree: true,
    comments: "",
    priority: "1",
  },

  {
    id: 8,
    firstname: "יהורם",
    lastname: "",
    phone: "0523343335",
    city: "תל אביב יפו",
    neighborhood: "פלורנטין",
    street: "העליה",
    homenumber: 4,
    adresscomments: "",
    additionalneeds: "",
    isproblematic: false,
    howmanypeople: "2",
    kosher: false,
    parve: false,
    vegan: true,
    sugerfree: false,
    lactosefree: false,
    glutenfree: true,
    peanutfree: false,
    nutsfree: true,
    comments: "",
    priority: "1",
  },
];

export default Addresses;
