const mockVolunteers = [
  {
    id: 1,
    firstName: 'רון',
    lastName: 'כוהן',
    phoneNumber: '0548543775',
    age: '15',
    city: 'תל אביב יפו',
    street: 'דובנוב 12',
    kosher: 'False',
    parve: 'False',
    vegan: 'True',
    sugerfree: 'False',
    lactosefree: 'False',
    glutenfree: 'True',
    peanutfree: 'False',
    nutsfree: 'True',
    howoften: '1',
    permissions: '3',
    avoidance:'',
    howyouheardofus:'שמעתי מחבר',
    strikes:'',
    comments:''
  },
  {
    firstName: 'דנה',
    lastName: 'לוי',
    phoneNumber: '0534445868',
    age: '23',
    city: 'תל אביב יפו',
    street: 'יצחק טבנקין 7',
    kosher: 'True',
    parve: 'True',
    vegan: 'False',
    sugerfree: 'True',
    lactosefree: 'False',
    glutenfree: 'False',
    peanutfree: 'True',
    nutsfree: 'True',
    howoften: '2',
    permissions: '0',
    avoidance:'',
    howyouheardofus:'מדיה חברתית',
    strikes:'',
    comments:''
  },
  {
    id: 3,
    firstName: 'דנית',
    lastName: 'מנור',
    phoneNumber: '0544395886',
    age: '20',
    city: 'כפר סבא',
    street: 'הגליל 8',
    kosher: 'False',
    parve: 'True',
    vegan: 'True',
    sugerfree: 'True',
    lactosefree: 'True',
    glutenfree: 'True',
    peanutfree: 'True',
    nutsfree: 'True',
    howoften: '1',
    permissions: '4',
    avoidance:'',
    howyouheardofus:'שמעתי מחבר',
    strikes:'',
    comments:''
  },
  {
    id: 4,
    firstName: 'שקד',
    lastName: 'שמש',
    phoneNumber: '0523459632',
    age: '30',
    city: 'חיפה',
    street: 'וילנסקי 4',
    kosher: 'False',
    parve: 'False',
    vegan: 'False',
    sugerfree: 'False',
    lactosefree: 'False',
    glutenfree: 'False',
    peanutfree: 'False',
    nutsfree: 'False',
    howoften: '1',
    permissions: '2',
    avoidance:'',
    howyouheardofus:'מדיה חברתית',
    strikes:'',
    comments:''
  },
  {
    id: 5,
    firstName: 'אמיר',
    lastName: 'חורב',
    phoneNumber: '0543691221',
    age: '28',
    city: 'חיפה',
    street: 'הפרחים 5',
    kosher: 'False',
    parve: 'False',
    vegan: 'True',
    sugerfree: 'False',
    lactosefree: 'True',
    glutenfree: 'False',
    peanutfree: 'True',
    nutsfree: 'True',
    howoften: '3',
    permissions: '2',
    avoidance:'',
    howyouheardofus:'אחר',
    strikes:'',
    comments:''
  },
  {
    id: 6,
    firstName: 'יובל',
    lastName: 'נורי',
    phoneNumber: '0523465581',
    age: '24',
    city: 'תל אביב יפו',
    street: 'רוטשילד 16',
    kosher: 'True',
    parve: 'True',
    vegan: 'True',
    sugerfree: 'True',
    lactosefree: 'False',
    glutenfree: 'False',
    peanutfree: 'False',
    nutsfree: 'False',
    howoften: '2',
    permissions: '3',
    avoidance:'',
    howyouheardofus:'כתבה',
    strikes:'',
    comments:''
  },

];

export default mockVolunteers;