const addresses = [
    {
       id: 1,
      firstName: 'חנה',
      lastName: 'סיגאוי',
      phone: '0548333375',
      city: 'תל אביב יפו',
      neighborhood:'הצפון הישן',
      street: 'סירקין',
      homenumber:'13',
      adresscomments:'מול קיוסק ציונה',
      additionalneeds:'שמיכות',
      isproblematic:'True',
      howmanypeople:'2',
      kosher: 'True',
      parve: 'False',
      vegan: 'False',
      sugerfree: 'True',
      lactosefree: 'False',
      glutenfree: 'False',
      peanutfree: 'False',
      nutsfree: 'True',
      comments:'גיל 18 ומעלה בלבד',
      priority:'1',
    },
    {
      id: 2,
      firstName: 'חדוה',
      lastName: 'אסולין',
      phone: '0542243775',
      city: 'תל אביב יפו',
      neighborhood:'נווה שאנן',
      street: 'לוינסקי',
      homenumber:'4',
      adresscomments:'',
      additionalneeds:'',
      isproblematic:'False',
      howmanypeople:'2',
      kosher: 'False',
      parve: 'False',
      vegan: 'True',
      sugerfree: 'False',
      lactosefree: 'False',
      glutenfree: 'True',
      peanutfree: 'False',
      nutsfree: 'True',
      comments:'',
      priority:'1',
    },
    {
      id: 3,
      firstName: 'אנה',
      lastName: 'כהן',
      phone: '0549543979',
      city: 'חיפה',
      neighborhood:'נווה שאנן',
      street: 'חניתה',
      homenumber:'27',
      adresscomments:'',
      additionalneeds:'',
      isproblematic:'False',
      howmanypeople:'2',
      kosher: 'False',
      parve: 'False',
      vegan: 'False',
      sugerfree: 'True',
      lactosefree: 'True',
      glutenfree: 'False',
      peanutfree: 'False',
      nutsfree: 'False',
      comments:'',
      priority:'2',
    },
    {
      id: 4,
      firstName: 'גידי',
      lastName: 'אברהמוב',
      phone: '0503443775',
      city: 'חיפה',
      neighborhood:'בת גלים',
      street: 'לוץ שרל',
      homenumber:'3',
      adresscomments:'',
      additionalneeds:'',
      isproblematic:'False',
      howmanypeople:'False',
      kosher: 'False',
      parve: 'False',
      vegan: 'False',
      sugerfree: 'False',
      lactosefree: 'False',
      glutenfree: 'False',
      peanutfree: 'False',
      nutsfree: 'False',
      comments:'',
      priority:'2'
    },
    {
      id: 5,
      firstName: 'הודיה',
      lastName: '',
      phone: '0540543005',
      city: 'כפר סבא',
      neighborhood:'אליעזר',
      street: 'טשרנחובסקי',
      homenumber: '24',
      adresscomments:'',
      additionalneeds:'',
      isproblematic:'False',
      howmanypeople:'3',
      kosher: 'False',
      parve: 'False',
      vegan: 'True',
      sugerfree: 'False',
      lactosefree: 'False',
      glutenfree: 'False',
      peanutfree: 'False',
      nutsfree: 'False',
      comments:'משפחה של 3 אנשים הבנות אוהבות עוגיות שוקולד',
      priority:'1',
    },
    {
      id: 6,
      firstName:'אדווה',
      lastName: 'כוהן',
      phone: '0528543115',
      city: 'תל אביב יפו',
      neighborhood:'נווה שאנן',
      street: 'הרכבת',
      homenumber:'4',
      adresscomments:'',
      additionalneeds:'',
      isproblematic:'False',
      howmanypeople:'2',
      kosher: 'False',
      parve: 'False',
      vegan: 'True',
      sugerfree: 'False',
      lactosefree: 'False',
      glutenfree: 'True',
      peanutfree: 'False',
      nutsfree: 'True',
      comments:'',
      priority:'1',
    },
  
    {
      id: 7,
      firstName:'אברהם',
      lastName: '',
      phone: '0528443115',
      city: 'תל אביב יפו',
      neighborhood:'פלורנטין',
      street: 'הרצל',
      homenumber:'4',
      adresscomments:'',
      additionalneeds:'',
      isproblematic:'False',
      howmanypeople:'2',
      kosher: 'False',
      parve: 'False',
      vegan: 'True',
      sugerfree: 'False',
      lactosefree: 'False',
      glutenfree: 'True',
      peanutfree: 'False',
      nutsfree: 'True',
      comments:'',
      priority:'1',
    },
  
      {
      id: 8,
      firstName:'יהורם',
      lastName: '',
      phone: '0523343335',
      city: 'תל אביב יפו',
      neighborhood:'פלורנטין',
      street: 'העליה',
      homenumber:'4',
      adresscomments:'',
      additionalneeds:'',
      isproblematic:'False',
      howmanypeople:'2',
      kosher: 'False',
      parve: 'False',
      vegan: 'True',
      sugerfree: 'False',
      lactosefree: 'False',
      glutenfree: 'True',
      peanutfree: 'False',
      nutsfree: 'True',
      comments:'',
      priority:'1',
    },
  ];
  
export default addresses;